Clean up

diff --git a/deploy/Dockerfile.alpine b/deploy/Dockerfile.alpine
--- a/deploy/Dockerfile.alpine
+++ b/deploy/Dockerfile.alpine
@@ -1,18 +1,8 @@
-# syntax=docker/dockerfile:experimental
-#
 # Build app
-#
-# The "syntax" line must be the first thing in the file, as it enables the
-# new syntax for caching, etc. see
-# https://docs.docker.com/develop/develop-images/build_enhancements/
-# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md
 
 ARG ELIXIR_VERSION=1.13.4
 ARG OTP_VERSION=24.3.4
-ARG NODE_VERSION=16.14.1
-# ARG NODE_VERSION=lts
-
-ARG ALPINE_VERSION=3.15.4
+ARG ALPINE_VERSION=3.15.3
 
 # By default, packages come from the APK index for the base Alpine image.
 # Package versions are consistent between builds, and we normally upgrade by
@@ -28,7 +18,7 @@ ARG APK_UPGRADE=":"
 # Docker registry for internal images, e.g. 123.dkr.ecr.ap-northeast-1.amazonaws.com/
 # If blank, docker.io will be used. If specified, should have a trailing slash.
 ARG REGISTRY=""
-# Registry for public base images, e.g. debian or alpine.
+# Registry for public images, e.g. debian, alpine, or postgres.
 # Public images may be mirrored into the private registry, with e.g. Skopeo
 ARG PUBLIC_REGISTRY=$REGISTRY
 
@@ -37,9 +27,6 @@ ARG BUILD_IMAGE_TAG=${ELIXIR_VERSION}-erlang-${OTP_VERSION}-alpine-${ALPINE_VERS
 
 ARG DEPLOY_IMAGE_NAME=${PUBLIC_REGISTRY}alpine
 ARG DEPLOY_IMAGE_TAG=$ALPINE_VERSION
-
-ARG INSTALL_IMAGE_NAME=$DEPLOY_IMAGE_NAME
-ARG INSTALL_IMAGE_TAG=$DEPLOY_IMAGE_TAG
 
 # App name, used to name directories
 ARG APP_NAME=app
@@ -59,13 +46,13 @@ ARG APP_GROUP_ID=$APP_USER_ID
 
 ARG LANG=C.UTF-8
 
-# ARG http_proxy
-# ARG https_proxy=$http_proxy
-
-# Build cache dirs
-# ARG MIX_HOME=/opt/mix
-# ARG HEX_HOME=/opt/hex
-# ARG XDG_CACHE_HOME=/opt/cache
+# Trivy vulnerability scanner
+# Fail for issues of severity = HIGH
+# ARG TRIVY_OPTS="--exit-code 1 --severity HIGH"
+# Fail for issues of severity = CRITICAL
+ARG TRIVY_OPTS="--exit-code 1 --severity CRITICAL"
+# Fail for any issues
+# ARG TRIVY_OPTS="-d --exit-code 1"
 
 # Elixir release env to build
 ARG MIX_ENV=prod
@@ -86,26 +73,22 @@ ARG APP_PORT=4000
 
 # Create build base image with OS dependencies
 FROM ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG} AS build-os-deps
-    # ARG http_proxy
-    # ARG https_proxy
-
     ARG APK_UPDATE
     ARG APK_UPGRADE
 
-    # Install tools and libraries to build binary libraries
-    # Not necessary for a minimal Phoenix app, but likely needed
+    ARG LANG
+    ENV LANG=$LANG
+
     # See https://wiki.alpinelinux.org/wiki/Local_APK_cache for details
     # on the local cache and need for the symlink
-    RUN --mount=type=cache,id=apk,target=/var/cache/apk \
+    RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
         set -exu && \
+        ln -s /var/cache/apk /etc/apk/cache && \
         $APK_UPDATE && $APK_UPGRADE && \
-        # Install build tools
-        # apk add --no-progress alpine-sdk && \
-        apk add --no-progress git build-base curl && \
         apk add --no-progress nodejs npm && \
-        # apk add --no-progress python3 && \
-        # Vulnerability checking
-        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
+        # Tools and libraries to build binary libraries
+        # apk add --no-progress alpine-sdk && \
+        apk add --no-progress git build-base
 
     # Database command line clients to check if DBs are up when performing integration tests
     # RUN apk add --no-progress postgresql-client mysql-client
@@ -116,57 +99,40 @@ FROM ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG} AS build-os-deps
     #     apk del .build-dependencies && rm -f msodbcsql*.sig mssql-tools*.apk
     # ENV PATH="/opt/mssql-tools/bin:${PATH}"
 
-# Get Elixir deps
+# Fetch and compile Elixir app deps
 FROM build-os-deps AS build-deps-get
-    # ARG http_proxy
-    # ARG https_proxy
-    ARG LANG
-    ARG MIX_ENV
     ARG APP_DIR
 
     WORKDIR $APP_DIR
 
-    # Get Elixir app deps
+    RUN mix do local.rebar --force, local.hex --force
+
+    # Copy only the minimum files needed for deps, improving caching
     COPY config ./config
     COPY mix.exs .
     COPY mix.lock .
 
-    # Install build tools and get app deps
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #     # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
-    RUN mix do local.rebar --force, local.hex --force
     RUN mix deps.get
 
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #    # --mount=type=cache,target=~/.cache/rebar3,sharing=locked \
     RUN mix esbuild.install
 
 # Create base image for tests
 FROM build-deps-get AS test-image
-    ARG LANG
     ARG APP_DIR
 
-    ENV LANG=$LANG \
-        HOME=$APP_DIR \
+    ENV HOME=$APP_DIR \
         MIX_ENV=test
-
-    # ARG MIX_HOME
-    # ARG HEX_HOME
-    # ARG XDG_CACHE_HOME
-    # ENV MIX_HOME=$MIX_HOME \
-    #     HEX_HOME=$HEX_HOME \
-    #     XDG_CACHE_HOME=$XDG_CACHE_HOME
 
     WORKDIR $APP_DIR
 
     # Compile deps separately from app, improving Docker caching
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #     # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
     RUN mix do local.rebar --force, local.hex --force
     RUN mix deps.compile
 
-    # COPY --if-exists coveralls.json .formatter.exs .credo.exs dialyzer-ignore ./
-    COPY .formatter.exs ./
+    # COPY .formatter.exs ./
+    # COPY ./coveralls.json ./
+    # COPY .credo.exs ./
+    # COPY dialyzer-ignore ./
 
     # Non-umbrella
     COPY lib ./lib
@@ -198,13 +164,11 @@ FROM build-deps-get AS deploy-release
     WORKDIR $APP_DIR
 
     # This does a partial compile.
-    # Doing "mix do compile, phx.digest, release" in a single stage is worse,
+    # Doing "mix do compile, assets.deploy" in a single stage is worse
     # because a single line of code changed causes a complete recompile.
     # With the stages separated most of the compilation is cached.
 
     # Compile deps separately from application for better caching
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #    # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
     RUN mix deps.compile
 
     # Compile assets the old way
@@ -230,10 +194,6 @@ FROM build-deps-get AS deploy-release
     COPY assets ./assets
     COPY priv ./priv
 
-    # mix.exs: "assets.deploy": ["esbuild default --minify", "phx.digest"]
-    # https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Digest.html
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #    # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
     RUN mix assets.deploy
 
     # Non-umbrella
@@ -242,14 +202,10 @@ FROM build-deps-get AS deploy-release
     # Umbrella
     # COPY apps ./apps
 
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #    # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
     RUN mix compile --warnings-as-errors
 
     # Build release
     COPY rel ./rel
-    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
-    #    # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
     RUN mix release "$RELEASE"
 
 # Create base image for deploy, with everything but the code release
@@ -272,13 +228,6 @@ FROM ${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_TAG} AS deploy-base
     RUN addgroup -g $APP_GROUP_ID -S "$APP_GROUP" && \
         adduser -u $APP_USER_ID -S "$APP_USER" -G "$APP_GROUP" -h "$HOME"
 
-    # Create app dirs
-    RUN mkdir -p "/run/${APP_NAME}" && \
-        # Make dirs writable by app
-        chown -R "${APP_USER}:${APP_GROUP}" \
-            # Needed for RELEASE_TMP
-            "/run/${APP_NAME}"
-
     # Install Alpine libraries needed at runtime
     # See https://wiki.alpinelinux.org/wiki/Local_APK_cache for details
     # on the local cache and need for the symlink
@@ -288,50 +237,52 @@ FROM ${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_TAG} AS deploy-base
         # Upgrading ensures that we get the latest packages, but makes the build nondeterministic
         $APK_UPDATE && $APK_UPGRADE && \
         # https://github.com/krallin/tini
-        # apk add tini && \
+        # apk add --no-progress tini && \
         # Make DNS resolution more reliable
         # https://github.com/sourcegraph/godockerize/commit/5cf4e6d81720f2551e6a7b2b18c63d1460bbbe4e
-        # apk add bind-tools && \
+        # apk add --no-progress bind-tools && \
+        # Support outbound TLS connections
+        apk add --no-progress ca-certificates && \
+        # apk add shared-mime-info tzdata && \
 
-        # Install openssl, allowing app to listen on HTTPS.
+        # Allow app to listen on HTTPS.
         # May not be needed if HTTPS is handled outside the application, e.g. in load balancer.
-        apk add openssl ncurses-libs
+        apk add --no-progress openssl && \
+        apk add --no-progress curses-libs
 
 # Create final app image which gets deployed
 FROM deploy-base AS deploy
-    ARG LANG
     ARG APP_DIR
     ARG APP_NAME
     ARG APP_USER
     ARG APP_GROUP
+    ARG APP_PORT
 
     ARG MIX_ENV=prod
     ARG RELEASE
 
-    ARG APP_PORT
-
     # Set environment vars used by the app
     # SECRET_KEY_BASE and DATABASE_URL env vars should be set when running the application
-    # maybe set COOKIE and other things
-    ENV LANG=$LANG \
-        HOME=$APP_DIR \
+    # Maybe set COOKIE and other things
+    ENV HOME=$APP_DIR \
         PORT=$APP_PORT \
         PHX_SERVER=true \
         RELEASE=$RELEASE \
+        # Writable tmp directory for releases
         RELEASE_TMP="/run/${APP_NAME}"
 
-    # Create dirs writable by app user
-    RUN mkdir -p "/run/${APP_NAME}" && \
+    RUN \
+        # Create app dirs
+        mkdir -p "/run/${APP_NAME}" && \
+        # Make dirs writable by app
         chown -R "${APP_USER}:${APP_GROUP}" \
+            # Needed for RELEASE_TMP
             "/run/${APP_NAME}"
 
     # USER $APP_USER
 
     # Setting WORKDIR after USER makes directory be owned by the user.
     # Setting it before makes it owned by root, which is more secure.
-    # The app needs to be able to write to a tmp directory on startup, which by
-    # default is under the release. This can be changed by setting RELEASE_TMP to
-    # /tmp or, more securely, /run/foo
     WORKDIR $APP_DIR
 
     # When using a startup script, copy to /app/bin
@@ -369,17 +320,23 @@ FROM deploy-base AS deploy
 
 
 # Scan image for security vulnerabilities
-FROM deploy as deploy-scan
+FROM deploy AS deploy-scan
+    ARG APK_UPDATE
+    ARG APK_UPGRADE
+    ARG TRIVY_OPTS
+    ARG APP_USER
+
     USER root
 
     RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
-        set -ex && \
+        set -exu && \
         $APK_UPDATE && $APK_UPGRADE && \
-        apk add curl && \
+        # Vulnerability checking
+        apk add --no-progress curl && \
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
 
     RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
-        set -ex && \
+        set -exu && \
         mkdir -p /sarif-reports && \
         # Succeed for issues of severity = HIGH
         # trivy filesystem $TRIVY_OPTS --format sarif -o /sarif-reports/trivy.high.sarif --exit-code 0 --severity HIGH --no-progress / && \
