Sync alpine

diff --git a/deploy/Dockerfile.alpine b/deploy/Dockerfile.alpine
--- a/deploy/Dockerfile.alpine
+++ b/deploy/Dockerfile.alpine
@@ -31,13 +31,6 @@ ARG DEPLOY_IMAGE_TAG=$ALPINE_VERSION
 ARG INSTALL_IMAGE_NAME=$DEPLOY_IMAGE_NAME
 ARG INSTALL_IMAGE_TAG=$DEPLOY_IMAGE_TAG
 
-# Run "apk upgrade" to update packages to a newer version than what is in the base image.
-# This ensures that we get the latest packages, but makes the build nondeterministic.
-# It is most useful when here is a vulnerability which is fixed in packages but
-# not yet released in an Alpine base image.
-# ARG APK_UPGRADE="apk upgrade --update-cache -a"
-ARG APK_UPGRADE=":"
-
 # App name, used to name directories
 ARG APP_NAME=app
 
@@ -56,13 +49,23 @@ ARG APP_GROUP_ID=$APP_USER_ID
 
 ARG LANG=C.UTF-8
 
+# By default, packages come from the APK index for the base Alpine image.
+# Package versions are consistent between builds, and we normally upgrade by
+# upgrading the Alpine version.
+ARG APK_UPDATE=":"
+ARG APK_UPGRADE=":"
+# If a vulnerability is fixed in packages but not yet released in an Alpine base image,
+# Then we can run update/upgrade as part of the build.
+# ARG APK_UPDATE="apk update"
+# ARG APK_UPGRADE="apk upgrade --update-cache -a"
+
 # ARG http_proxy
 # ARG https_proxy=$http_proxy
 
 # Build cache dirs
-ARG MIX_HOME=/opt/mix
-ARG HEX_HOME=/opt/hex
-ARG XDG_CACHE_HOME=/opt/cache
+# ARG MIX_HOME=/opt/mix
+# ARG HEX_HOME=/opt/hex
+# ARG XDG_CACHE_HOME=/opt/cache
 
 # Elixir release env to build
 ARG MIX_ENV=prod
@@ -91,13 +94,17 @@ FROM ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG} AS build-os-deps
 
     # Install tools and libraries to build binary libraries
     # Not necessary for a minimal Phoenix app, but likely needed
-    RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
-        ln -s /var/cache/apk /etc/apk/cache && \
-        apk update && $APK_UPGRADE && \
-        # apk add alpine-sdk && \
-        apk add --no-progress git build-base && \
-        apk add curl && \
-        apk add nodejs npm && \
+    # See https://wiki.alpinelinux.org/wiki/Local_APK_cache for details
+    # on the local cache and need for the symlink
+    RUN --mount=type=cache,id=apk,target=/var/cache/apk \
+        set -ex && \
+        $APK_UPDATE && $APK_UPGRADE && \
+        # Install build tools
+        # apk add --no-progress alpine-sdk && \
+        apk add --no-progress git build-base curl && \
+        apk add --no-progress nodejs npm && \
+        # apk add --no-progress python3 && \
+        # Vulnerability checking
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
 
 FROM build-os-deps AS build-deps-get
@@ -115,11 +122,13 @@ FROM build-os-deps AS build-deps-get
     COPY mix.lock .
 
     # Install build tools and get app deps
-    RUN --mount=type=cache,target=~/.hex/packages/hexpm,sharing=locked \
-        --mount=type=cache,target=~/.cache/rebar3,sharing=locked \
-        mix do local.rebar --force, local.hex --force, deps.get
-        # mix do local.rebar --force, local.hex --force, deps.get --only $MIX_ENV
+    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
+    #     # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
+    RUN mix do local.rebar --force, local.hex --force
+    RUN mix deps.get
 
+    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
+    #    # --mount=type=cache,target=~/.cache/rebar3,sharing=locked \
     RUN mix esbuild.install
 
 # Base image used for running tests
@@ -127,31 +136,39 @@ FROM build-deps-get AS test-image
     ARG LANG
     ARG APP_DIR
 
-    ARG MIX_HOME
-    ARG HEX_HOME
-    ARG XDG_CACHE_HOME
-
     ENV LANG=$LANG \
         HOME=$APP_DIR \
         MIX_ENV=test
 
-    ENV MIX_HOME=$MIX_HOME \
-        HEX_HOME=$HEX_HOME \
-        XDG_CACHE_HOME=$XDG_CACHE_HOME
+    # ARG MIX_HOME
+    # ARG HEX_HOME
+    # ARG XDG_CACHE_HOME
+    # ENV MIX_HOME=$MIX_HOME \
+    #     HEX_HOME=$HEX_HOME \
+    #     XDG_CACHE_HOME=$XDG_CACHE_HOME
 
     WORKDIR $APP_DIR
 
-    # Instead of copying sources, could use bind mount, e.g.
-    # RUN --mount=target=.
-    # see https://adoptingerlang.org/docs/production/docker/#efficient-caching
+
+    # Non-umbrella
     COPY lib ./lib
     COPY priv ./priv
     COPY test ./test
     COPY bin ./bin
 
-    RUN --mount=type=cache,target=~/.hex/packages/hexpm,sharing=locked \
-        --mount=type=cache,target=~/.cache/rebar3,sharing=locked \
-        mix compile --warnings-as-errors
+    # Umbrella
+    # COPY apps ./apps
+    # COPY priv ./priv
+
+    # RUN --mount=type=cache,id=hex,target=/opt/hex,sharing=locked \
+    #    # --mount=type=cache,id=rebar,target=~/.cache/rebar3,sharing=locked \
+    RUN mix compile --warnings-as-errors
+
+    # For umbrella, using `mix cmd` ensures each app is compiled in
+    # isolation https://github.com/elixir-lang/elixir/issues/9407
+    # RUN --mount=type=cache,target=~/.hex/packages/hexpm,sharing=locked \
+    #     --mount=type=cache,target=~/.cache/rebar3,sharing=locked \
+    #     mix cmd mix compile --warnings-as-errors
 
 # Build Phoenix assets
 FROM build-os-deps AS assets
@@ -222,23 +239,26 @@ FROM ${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_TAG} AS deploy-release
     # maybe set COOKIE and other things
     ENV LANG=$LANG \
         HOME=$APP_DIR \
-        RELEASE_TMP="/run/$APP_NAME" \
-        RELEASE=${RELEASE} \
-        PORT=$APP_PORT
+        PORT=$APP_PORT \
+        PHX_SERVER=true \
+        RELEASE=$RELEASE \
+        RELEASE_TMP="/run/${APP_NAME}"
 
     # Install Alpine libraries needed at runtime
     # See https://wiki.alpinelinux.org/wiki/Local_APK_cache for details
     # on the local cache and need for the symlink
     RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
+        set -ex && \
         ln -s /var/cache/apk /etc/apk/cache && \
         # Upgrading ensures that we get the latest packages, but makes the build nondeterministic
-        apk update && $APK_UPGRADE && \
+        $APK_UPDATE && $APK_UPGRADE && \
         # https://github.com/krallin/tini
         # apk add tini && \
         # Make DNS resolution more reliable
         # https://github.com/sourcegraph/godockerize/commit/5cf4e6d81720f2551e6a7b2b18c63d1460bbbe4e
         # apk add bind-tools && \
-        # Install openssl, allowing the app to listen on HTTPS.
+
+        # Install openssl, allowing app to listen on HTTPS.
         # May not be needed if HTTPS is handled outside the application, e.g. in load balancer.
         apk add openssl ncurses-libs
 
@@ -268,8 +288,8 @@ FROM ${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_TAG} AS deploy-release
     USER $APP_USER
 
     # Chown files while copying. Running "RUN chown -R app:app /app"
-    # adds an extra layer which is about 10Mb, a huge difference when the
-    # image for a new phoenix app is around 20Mb.
+    # adds an extra layer which is about 10Mb, a huge difference if the
+    # app image is around 20Mb.
 
     # TODO: For more security, change specific files to have group read/execute
     # permissions while leaving them owned by root
@@ -281,8 +301,12 @@ FROM ${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_TAG} AS deploy-release
 
     EXPOSE $PORT
 
-    # "bin" is the directory under the unpacked release, and "prod" is the name of the release
+    # "bin" is the directory under the unpacked release, and "prod" is the name
+    # of the release
     ENTRYPOINT ["bin/prod"]
+
+    # Run under init to avoid zombie processes
+    # https://github.com/krallin/tini
     # ENTRYPOINT ["/sbin/tini", "--", "bin/prod"]
 
     # Run app in foreground
@@ -293,20 +317,22 @@ FROM deploy as deploy-scan
     USER root
 
     RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
+        set -ex && \
         apk add curl && \
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
 
     RUN --mount=type=cache,id=apk,target=/var/cache/apk,sharing=locked \
-        --mount=type=cache,target=/root/.cache/trivy,sharing=locked \
+        set -ex && \
         # Succeed for issues of severity = HIGH
-        trivy filesystem --exit-code 0 --severity HIGH --no-progress / && \
-        # Fail build if there are any issues of severity = CRITICAL
-        trivy filesystem --exit-code 1 --severity CRITICAL --no-progress /
-        # Fail build if there are any issues
+        # trivy filesystem $TRIVY_OPTS --format sarif -o /sarif-reports/trivy.high.sarif --exit-code 0 --severity HIGH --no-progress / && \
+        trivy filesystem $TRIVY_OPTS --exit-code 0 --severity HIGH --no-progress / && \
+        # Fail for issues of severity = CRITICAL
+        # trivy filesystem $TRIVY_OPTS --format sarif -o /sarif-reports/trivy.sarif --exit-code 1 --severity CRITICAL --no-progress /
+        # Fail for any issues
         # trivy filesystem -d --exit-code 1 --no-progress /
+        trivy filesystem --format sarif -o /sarif-reports/trivy.sarif --no-progress $TRIVY_OPTS --no-progress /
 
-        # && curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin \
-        # && grype -vv --fail-on medium dir:/ \
+        # grype -vv --fail-on medium dir:/ \
 
 # Copy build artifacts to host
 FROM scratch as artifacts
